// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_vsdQn5EElNbam3W28FKM8XmwAI4QT6Y',
    appId: '1:752437627626:web:476440529a768d72582593',
    messagingSenderId: '752437627626',
    projectId: 'flutterfire-aa00e',
    authDomain: 'flutterfire-aa00e.firebaseapp.com',
    storageBucket: 'flutterfire-aa00e.appspot.com',
    measurementId: 'G-LFYV8S9ZZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkK_FZN4OoZahRU7JxkF2ddz1kci1cBLg',
    appId: '1:752437627626:android:7b0db357760f6f64582593',
    messagingSenderId: '752437627626',
    projectId: 'flutterfire-aa00e',
    storageBucket: 'flutterfire-aa00e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuDzgFxPkdE6_DJyuignBmnK9a8-o8_Ac',
    appId: '1:752437627626:ios:ef7b366b369f8283582593',
    messagingSenderId: '752437627626',
    projectId: 'flutterfire-aa00e',
    storageBucket: 'flutterfire-aa00e.appspot.com',
    iosClientId: '752437627626-28ne1a5p8js386mc79b0dq6gq7a3d6bd.apps.googleusercontent.com',
    iosBundleId: 'com.myflutterapp.flutterfireInit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuDzgFxPkdE6_DJyuignBmnK9a8-o8_Ac',
    appId: '1:752437627626:ios:ef7b366b369f8283582593',
    messagingSenderId: '752437627626',
    projectId: 'flutterfire-aa00e',
    storageBucket: 'flutterfire-aa00e.appspot.com',
    iosClientId: '752437627626-28ne1a5p8js386mc79b0dq6gq7a3d6bd.apps.googleusercontent.com',
    iosBundleId: 'com.myflutterapp.flutterfireInit',
  );
}
